### ISSUE TITLE
There is a problem with typing '/' and then typing text, which causes text to overlap.

### ISSUE THREAD

**Issue by yuluovin** [1oopstudio/support.ohmymd.app#1]
Hi developers, I was lucky enough to be the first user of the release and experience the product. The input experience was excellent. But there is a small UI display issue, when you type "/" and then type the text while the popup is still open, the text will overlap the prompt text.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/29879876/205556798-b3c572e3-ddd4-4cba-affe-895a349def28.png">

**Comment by imczdev** [comment]
Ok, we will fix it at next version

**Comment by imczdev** [comment]
update to 0.1.5 version pls
