### ISSUE TITLE
某种情况下界面灰白

### ISSUE THREAD

**Issue by Tlntin** [1oopstudio/support.ohmymd.app#10]
**bug描述**
清晰而简明地描述您的问题

**复现**
复现该行为的步骤:
1. 打开ohmymd软件
2. 右键托盘，打开`关于`（此时不关闭）;
3. 右键托盘，显示;
4. 右键托盘，设置; 或者点击头像进设置。
5. 设置界面不显示，灰色。

**截图(选填)**
![image](https://user-images.githubusercontent.com/28218658/224028102-0d25834e-e1d1-4085-a141-55fc34bd4be7.png)

**基础信息**
 - OS: Ubuntu
 - Version 22.04

**备注(选填)**
任何你想写的

**Comment by imczdev** [comment]
> **bug描述** 清晰而简明地描述您的问题
> 
> **复现** 复现该行为的步骤:
> 
> 1. 打开ohmymd软件
> 2. 右键托盘，打开`关于`（此时不关闭）;
> 3. 右键托盘，显示;
> 4. 右键托盘，设置; 或者点击头像进设置。
> 5. 设置界面不显示，灰色。
> 
> **截图(选填)** ![image](https://user-images.githubusercontent.com/28218658/224028102-0d25834e-e1d1-4085-a141-55fc34bd4be7.png)
> 
> **基础信息**
> 
> * OS: Ubuntu
> * Version 22.04
> 
> **备注(选填)** 任何你想写的

我们会尽快复现进行修改，在被修复之前我们希望一直打开该issue

**Comment by imczdev** [comment]
该问题我们已经在0.6.0修复了，如果你是Linux，或者macos可能需要全新安装（卸载安装）（linux与macos自动更新属于增量更新）
