### ISSUE TITLE
后续是否有支持vim编辑模式的计划

### ISSUE THREAD

**Issue by Q2035** [1oopstudio/support.ohmymd.app#11]
如题

**Comment by imczdev** [comment]
> 如题

Oh Mymd目前本事就是一个很小众的软件，我觉得vim党更是少有极客的钟爱，两者的结合可能更少。目前我们不能将有限的时间投入到这方面，希望理解。

Oh Mymd本身定位是一个笔记类的应用，而vim更像是代码或者文本的编辑软件。因此可能短时间内也没有这方面的计划。
