### ISSUE TITLE
创建文件夹后，在根目录创建的文档就不能直接切换过去了，只能退出软件重新打开。

### ISSUE THREAD

**Issue by yuanphoenix** [1oopstudio/support.ohmymd.app#12]
**bug描述**
点击 Oh Mymd文件夹没有反应
**复现**
复现该行为的步骤:
1.点击创建的文件夹即可

**截图(选填)**
有个截图就太好了
![image](https://user-images.githubusercontent.com/32676100/226094466-0d70b74b-f29e-48f7-a877-afc8e0f2f9e3.png)
回不到这个界面了
![屏幕截图 2023-03-18 162754](https://user-images.githubusercontent.com/32676100/226094619-15d6a8e2-5b1d-49df-9ed8-6aadb7c74dfb.png)

**基础信息**
 - OS: win11

**备注(选填)**
任何你想写的

**Comment by imczdev** [comment]
> **bug描述** 点击 Oh Mymd文件夹没有反应 **复现** 复现该行为的步骤: 1.点击创建的文件夹即可
> 
> **截图(选填)** 有个截图就太好了 ![image](https://user-images.githubusercontent.com/32676100/226094466-0d70b74b-f29e-48f7-a877-afc8e0f2f9e3.png) 回不到这个界面了 ![屏幕截图 2023-03-18 162754](https://user-images.githubusercontent.com/32676100/226094619-15d6a8e2-5b1d-49df-9ed8-6aadb7c74dfb.png)
> 
> **基础信息**
> 
> * OS: win11
> 
> **备注(选填)** 任何你想写的

笔记的根目录是不支持点击的。我们不建议在笔记的根目录创建笔记，因此这可能不是一个issue
