### ISSUE TITLE
编辑页面可以直接导出pdf吗？

### ISSUE THREAD

**Issue by Yang-SH** [1oopstudio/support.ohmymd.app#13]
编辑页面可以直接导出pdf吗？
不然每次导出都需要修改文件目录，比较麻烦

**Comment by imczdev** [comment]
> 编辑页面可以直接导出pdf吗？ 不然每次导出都需要修改文件目录，比较麻烦

我没太懂你的意思，能详细说一下吗？中间栏（笔记栏）右键就可以导出啊

**Comment by Yang-SH** [comment]
![image](https://github.com/1oopstudio/support.ohmymd.app/assets/23449308/a36aaf86-de3e-4550-9d18-87fd7e3f3810)
比如我直接打开一个md文件，是找不到导出pdf选项的

**Comment by imczdev** [comment]
> ![image](https://user-images.githubusercontent.com/23449308/258693781-a36aaf86-de3e-4550-9d18-87fd7e3f3810.png) 比如我直接打开一个md文件，是找不到导出pdf选项的

这里确实没有导出功能，我会在下个版本加上导出功能。应该是在本月中旬的样子发布出来。

如果没有疑问了，请关闭该issue
