### ISSUE TITLE
mac版本程序不能退出

### ISSUE THREAD

**Issue by maybe2017** [1oopstudio/support.ohmymd.app#3]
操作流程：mac版本，关闭掉编辑界面，dock选择软件图标，右键点击多次退出，均无法正常退出，也不能再打开编辑界面。

**Comment by imczdev** [comment]
1. 单击顶部菜单栏软件tray激活主界面.
2. 双指点击顶部菜单栏,选择exit菜单退出软件
这两项操作完成上面您的操作疑惑.

我们将在后面版本优化您的建议,给dock栏提供更多操作交互.
非常感谢您的反馈.

**Comment by imczdev** [comment]
我们已经完善优化了您的建议，提供了更多的dock栏操作交互.
