### ISSUE TITLE
关于云同步的问题

### ISSUE THREAD

**Issue by dida1024** [1oopstudio/support.ohmymd.app#7]
经过短暂的体验我似乎没有找到云同步的入口

可能需要一个对于云同步的专门部分

我觉得应该允许用户关闭云同步或者同步到github上确保数据安全

**Comment by KunerRick** [comment]
> 经过短暂的体验我似乎没有找到云同步的入口
> 
> 可能需要一个对于云同步的专门部分
> 
> 我觉得应该允许用户关闭云同步或者同步到github上确保数据安全

当前我们的云同步逻辑为登录之后，自动启用文件云同步，暂时没有开放对云同步的配置。后续计划将云同步功能进一步扩展，让用户能够自主配置云同步方式。
