### ISSUE TITLE
对于文件的显示问题

### ISSUE THREAD

**Issue by dida1024** [1oopstudio/support.ohmymd.app#8]
按照现有的结构是将一个文件夹分为了两部分
一边显示目录，一边显示目录里的md文件

这样做有一些小问题是我遇到的
* 无法显示目录里的文件
* 无法从左侧的目录栏里知道里面是否有md文件
* 无法收缩，有时候两栏太占空间了

我个人的小建议
* 如果可以只用一栏显示目录和里面的文件以及图片是否更简洁高效
* 添加的时候是否让用户选择添加的类型，比如：添加文件，添加目录
* 加一个自动保存呗

**Comment by imczdev** [comment]
您的建议和反馈我们已经收到，后续我们将回复我们的修复和改进方案

**Comment by imczdev** [comment]
> 按照现有的结构是将一个文件夹分为了两部分 一边显示目录，一边显示目录里的md文件
> 
> 这样做有一些小问题是我遇到的
> 
> * 无法显示目录里的文件
> * 无法从左侧的目录栏里知道里面是否有md文件
> * 无法收缩，有时候两栏太占空间了
> 
> 我个人的小建议
> 
> * 如果可以只用一栏显示目录和里面的文件以及图片是否更简洁高效
> * 添加的时候是否让用户选择添加的类型，比如：添加文件，添加目录
> * 加一个自动保存呗

Q:  无法显示目录里的文件
A:  目录侧只显示目录，不展示具体笔记

Q: 无法从左侧的目录栏里知道里面是否有md文件
A: 我们将在目录侧对应的目录添加该目录下笔记数量.

Q: 无法收缩，有时候两栏太占空间了
A: 我们考虑提供专注模式。

Q: 如果可以只用一栏显示目录和里面的文件以及图片是否更简洁高效
A: 暂不考虑合并目录和笔记

Q: 添加的时候是否让用户选择添加的类型，比如：添加文件，添加目录
A: 目录侧添加的则是目录，笔记侧添加的则是笔记

Q: 加一个自动保存呗
A：目前切换笔记会自动保存，后期根据反馈数量是否添加自动保存

**Comment by dida1024** [comment]
> > 按照现在的结构是将一个文件夹分为两部分 一边显示目录，一边显示目录里的md文件
> > 这样做有一些小问题是我遇到的
> > 
> > * 无法显示目录里的文件
> > * 无法从左边的目录栏里知道里面是没有md文件
> > * 无法收窄，有时两栏太占空间了
> > 
> > 我个人的小建议
> > 
> > * 如果可以只用一根显示目录和里面的文件以及图片是否更简洁高效
> > * 添加的时候是否让用户选择添加的类型，比如：添加文件，添加目录
> > * 加一个自动保存呗
> 
> Q: 无法显示目录里的文件 A: 目录侧只显示目录，不显示实体笔记本
> 
> Q: 无法从左边的目录栏里知道里面是否有md 文件
> 
> Q: 无法收窄，有时两栏太占空间了 A: 我们考虑提供专用注模。
> 
> Q: 如果可以只用一根显示目录和里面的文件以及图片是否更简洁高效 A: 暂不考虑合并目录和笔记
> 
> Q: 添加的时候是否让用户选择添加的类型，比如：添加文件，添加目录 A: 目录旁边添加的则是目录，笔记本旁边添加的则笔
> 
> Q: 加一个自动保存嘛 A：目前切换笔记本会自动保存，后期根据反馈数量是否添加自动保存

Q: 无法从左边的目录栏里知道里面是否有md
文件
这里有个问题，文件里并不能看到图片类型的文件，只能看到md格式的文件
