### ISSUE TITLE
是否考虑web版本或提供部署到docker上

### ISSUE THREAD

**Issue by sikenali** [1oopstudio/support.ohmymd.app#9]
RT

**Comment by imczdev** [comment]
> RT

Q. 是否提供web版本？
A. 因为browser没有访问本地文件系统的api，可能无法提供web版本来阅读和编辑本地文件。

**Comment by sikenali** [comment]
好的，感谢回复。

**Comment by imczdev** [comment]
> 好的，感谢回复。

如果相同类型的需求出现多次的话，可能会考虑通过node + browser 实现这个需求
